apiVersion: v2
name: argo-events
version: 0.0.1
description: Argo Events glyph for event-driven workflows
home: https://github.com/kast-spells
sources:
  - https://github.com/kast-spells/kast-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org