# glyphs:
#   aws:
#     un-policy:
#       type: iam-policy
#       actions:
#         - s3:ListBucket
#         - s3:GetObject
#       resources:
#         - arn:aws:s3:::example-bucket
#       name: kast-un-role #optional