lexicon:
  dev-eks-cluster:
    type: k8s-cluster
    labels:
      environment: development
      region: us-west-1
      provider: aws
      default: book
    clusterURL: https://SARLANGAOIDC.gr7.us-west-1.eks.amazonaws.com
    oidcID: SARLANGAOIDC
    region: us-west-1
    accountID: "323636678935"
  aws-iam-policy-secrets-manager:
    type: aws-iam-policy
    arn: iam-policy-secretsdasdadasdadsa
    labels:
      resources: secret-manager
      environment: development
      region: us-west-1
      provider: aws
  aws-iam-policy-s3:
    type: aws-iam-policy
    arn: iam-policy-s3sasasdas
    labels:
      resources: s3
      environment: development
      region: us-west-1
      provider: aws


glyphs:
  aws:
    un-role:
      type: iam-oidc-k8s-role
      oidcID: SARLANGAOIDC
      nameOverride: kast-un-role #optional
      policies:
        - name: kast-un-policy
          selector:
            resources: secret-manager
        - name: aws-iam-policy-s3
          selector:
            resources: s3