# kast - Kubernetes arcane spelling technology
# Copyright (C) 2023 namenmalkv@gmail.com
# Licensed under the GNU GPL v3. See LICENSE file for details.

name: keycloak-basic-user

glyphs:
  keycloak:
    - type: user
      name: test-user-john
      email: john.doe@test.local
      username: john.doe
      firstName: John
      lastName: Doe
      realmRef: test-realm
      enabled: true
      emailVerified: true
      groups:
        - engineering
        - developers
