# kast - Kubernetes arcane spelling technology
# Copyright (C) 2023 namenmalkv@gmail.com
# Licensed under the GNU GPL v3. See LICENSE file for details.

name: keycloak-basic-group

glyphs:
  keycloak:
    - type: group
      name: test-group-engineering
      scopeName: engineering
      realmRef: test-realm
      realmRoles:
        - developer
        - user
      clientRoles:
        - clientId: vault
          roles:
            - admin
            - editor
