apiVersion: v2
name: certManager
version: 1.0.0
description: certmanager glyphs for kast
home: https://github.com/runik-spells
sources:
  - https://github.com/runik-spells/runik-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org
