name: covenant-simple-users

covenant:
  realm:
    name: test-realm
    displayName: "Test Realm for Users"

# Test data structure - using bookrack symlink
# This example will read from bookrack/covenant/
# We test that covenant can properly read and process user data
