apiVersion: v2
name: microspell
version: 0.0.1
description: Opinionated microservice deployment chart with Vault, Istio, and monitoring integration
home: https://github.com/kast-spells
sources:
  - https://github.com/kast-spells/kast-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org