# kast - Kubernetes arcane spelling technology
# Copyright (C) 2023 namenmalkv@gmail.com
# Licensed under the GNU GPL v3. See LICENSE file for details.

# LoadBalancer Service Example  
# Tests summon glyph LoadBalancer service configuration

name: public-api

service:
  enabled: true
  type: LoadBalancerSpecial
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP  
      name: https
      nodePort: 30443