# ServiceAccount Example
# Tests summon glyph serviceAccount template generation

name: worker-service

serviceAccount:
  enabled: true
  name: custom-worker-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/worker-role
    gcp.workload-identity: worker@project.iam.gserviceaccount.com