# kast - Kubernetes arcane spelling technology
# Copyright (C) 2023 namenmalkv@gmail.com
# Licensed under the GNU GPL v3. See LICENSE file for details.

glyphs:
  gcp:
    - type: firewall
      name: allow-ssh
      rules:
        allow:
          - protocol: tcp
            ports:
            - "22"
            - "42022"
      networkRef: jorge