# kast - Kubernetes arcane spelling technology
# Copyright (C) 2023 namenmalkv@gmail.com
# Licensed under the GNU GPL v3. See LICENSE file for details.

glyphs:
  gcp:
    - type: subnet
      networkRef: jorge
      name: allow-ssh
      cidr: 10.12.128.0/22
      region: us-east1
      description: a nice long string
      