apiVersion: v2
name: gcp
version: 1.0.0
description: this has all the definitions of gcp infrastructure
home: https://github.com/runik-spells
sources:
  - https://github.com/runik-spells/runik-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org