apiVersion: v2
name: summon
version: 1.2.5
description: Kubernetes workload deployment chart for Deployments, StatefulSets, Jobs, CronJobs, and DaemonSets
home: https://github.com/runik-spells
sources:
  - https://github.com/runik-spells/runik-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org